/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Campaign custom colors
        navy: {
          DEFAULT: '#0B3D5C',
          50: '#E6F0F5',
          100: '#CCE0EB',
          200: '#99C2D7',
          300: '#66A3C3',
          400: '#3385AF',
          500: '#0B3D5C',
          600: '#09314A',
          700: '#072537',
          800: '#041825',
          900: '#020C12',
        },
        teal: {
          DEFAULT: '#1A6B6B',
          50: '#E6F2F2',
          100: '#CCE5E5',
          200: '#99CCCC',
          300: '#66B2B2',
          400: '#339999',
          500: '#1A6B6B',
          600: '#155656',
          700: '#104040',
          800: '#0A2B2B',
          900: '#051515',
        },
        ocean: {
          DEFAULT: '#2E8B9A',
          50: '#E9F5F7',
          100: '#D3EBEF',
          200: '#A7D7DF',
          300: '#7BC3CF',
          400: '#4FAFBF',
          500: '#2E8B9A',
          600: '#256F7B',
          700: '#1C535C',
          800: '#12383E',
          900: '#091C1F',
        },
        gold: {
          DEFAULT: '#D4A84B',
          50: '#FBF6E9',
          100: '#F7EDD3',
          200: '#EFDBA7',
          300: '#E7C97B',
          400: '#DFB74F',
          500: '#D4A84B',
          600: '#AA863C',
          700: '#7F642D',
          800: '#55431E',
          900: '#2A210F',
        },
        palm: {
          DEFAULT: '#2D7A4A',
          50: '#E9F5ED',
          100: '#D3EBDB',
          200: '#A7D7B7',
          300: '#7BC393',
          400: '#4FAF6F',
          500: '#2D7A4A',
          600: '#24623B',
          700: '#1B492C',
          800: '#12311D',
          900: '#09180F',
        },
        sand: {
          DEFAULT: '#F5E6D3',
          50: '#FDFAF7',
          100: '#F5E6D3',
          200: '#EBCDA7',
          300: '#E1B47B',
          400: '#D79B4F',
          500: '#CD8223',
          600: '#A4681C',
          700: '#7B4E15',
          800: '#52340E',
          900: '#291A07',
        },
        charcoal: '#1A1A2E',
        slate: '#4A5568',
      },
      fontFamily: {
        serif: ['Playfair Display', 'Georgia', 'serif'],
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        campaign: "0 4px 20px rgba(11, 61, 92, 0.15)",
        'campaign-lg': "0 8px 40px rgba(11, 61, 92, 0.2)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "fade-in-up": "fade-in-up 0.6s ease-out forwards",
        "fade-in": "fade-in 0.4s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
